name: linter-check

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install
        run: make install
      - name: run linter
        run: make lint